---
title: Luxembourg model collection
---

What will my collection look like on arrival in Luxembourg?

### Warhammer Fantasy Chaos Army

Five painted Chaos Knights

16 painted Chaos Warriors

Three painted Ogres

Approx 25 metal unpainted Chaos Warriors

    - 8 warriors of Nurgle

    - 8 warriors of Tzeentch

    - Bits to make another 10 or so warriors

12 unpainted Chaos marauders

Three Chaos knights, unpainted

Archaon, metal, unpainted

Crom the Conquerer, unpainted

Mounted Exalted Champion of Khorne

Aspiring Champion of Khorne

Mounted Exalted Champion of Nurgle

Mounted Exalted Champion of Tzeentch

Six metal Chaos warhounds

### Mordheim

Sisters of Sigmar warband

Witchhunters warband

### 40k

Five Chaos Terminators

10 Ork Commandos

Eldar Seer Council

20 GSC Neophyte hybrids

Nine unassembled Space marines (mix of Assault, Intercessors, Infiltrators)

### Inq28

Escher warband

Goliath warband

So many 


### AoS

Yndrasta

Three Praetors

Three Annihilators

Three HQ (Leader, wizard, banner)