---
title: "Project Master"
---

I've come to the realisation that while other people seem to collect and paint based on a faction or a game system, my projects are possibly best organised by experimentation in style. For example:

Chaos Warriors, The Old World/6th Edition: A realism project focused on learning to accurately capture the look and feel of metal, but also skin and cloth. Basing is key: like model train builders, I want realistic looking bases that depict rugged farmland. I've mentioned in an older Hobby Diary entry that Warriors of Chaos are at their most frightening when appearing at the edge of *your* village (rather than depicted out in the distant Wastes). I've followed Koltti's Patreon and learned a lot about this style, and managed to do a lot of it in my own way using layers of contrast paints to build up depth. 

Emperor's Children, The Achillian Majesty: A converting project. Interesting, but ultimately one I'd consider a failure. While I did manage to build basically a full army where every model is a conversion (some of which I'm very happy with), I don't think I met my original brief of "Mixing the insanity of Chaos with decadence". I failed to scult anything particularly fine or detailed, I didn't include any religious iconography or art (here I should have included extravagent banners, organ pipes, sculptures etc.,). This project also took an unexpected turn towards contrast paints, and I'm distinctly unhappy with the paint jobs on 99% of these models. I think putting this thought to page has given me permission to cannabilise these models for:

Heretic Astartes, Renegades: Gouache and oil paints, as per Totally_Not_Panicking, though I'm not quite hitting his style - I'm no-where near as loose as he is, and I can feel it in the result. Still, I'm happy with the outcome for the initial 10 models. 
