---
title: Vampire Counts
---

I just purchased, via job lot, a little over 2,000 points worth of Vampire Counts for the Old World. While it wasn't exactly something I'd planned to do, Vampire Counts (for Old World) or SoulBlight GraveLords (for AoS) *are* something I've spent a fair bit of time thinking and planning on. In fact, I already own a few Soulblight models: 

- The start collecting box: A wight on steed, five black knights, and 20 Grave guard. 
- The Vampire Underworlds set of four models (too large for either AoS or Old world).
- The villains and enemies from Cursed City, which is what started my initial interest in the faction. 

I've also written a fair amount of background in my previous writing format (Hobby Diary, a collection of txt documents): 

- A character called the Soul-Time Broker, who is on their way towards Lichedom. 
- The Revered Dead: a faction for AoS.
- A general sort of idea of the Vampire Court, an eclectic mix of Vampire Nobles who are out on a hunting party. Think Aristocratic Fox or Pheasant hunt, with hounds and retainers and all members of the court out for a day of sport. 

Roughly, this job lot includes:

- VC on Zombie Dragon
- Strigoi Ghoul King
- Strigoi Ghoul King with wings (on 50mm base, therefore could be played as a monstrous Varghulf)
- Banshee
- 40 Crypt ghouls
- 6 Vargheists
- 6 Crypt Horrors
- 10 Dire Wolves
- 5 Blood Knights

This already totals more than 2,000 points. When combined with my Start Collecting box (which will need to be rebased), this will be a hugely flexible project. 

