project:
  type: website
  output-dir: docs

website:
  title: "My Website"
#  sidebar:
#    style: "docked"
#    type: "dark"
#    search: true
#    contents: auto

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hobby_diary/index.qmd
        text: Hobby Diary
      - href: hobby_diary/001_Astartes.qmd
        text: Hobby Diary
      - href: projects/index.qmd
        text: Projects


format:
  html:
#    theme: cosmo
    css: styles.css
    toc: true

