project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    type: "dark"
    search: true
    contents: auto



format:
  html:
    theme:
    - cosmo
    - FaT_custom.scss
    toc: true



