---
title: "Feuds and Truces"
author: Duke of Westvale
date: 2025-09-28
---

"Politics: gangs, wars, truces. Nothing I didn't already know."

- Tommy Shelby, Peaky Blinders


# Introduction

I was first introduced to Warhammer as a game and hobby sometime around 2001. I spent hours and *hours* building and painting models, and even more time reading and re-reading a handful of White Dwarf magazines. Like many people, when I finished high school and went to University I put the hobby aside for awhile. In 2016 I picked it back up again when I realised some friends were also interested. Between 2016 and 2020 I rather unsuccessfully collected, painted and played warhammer 40k. At the very end of 2019 I discovered an overlapping group of online sub-communities of warhammer hobbyists who treated the game very differently. These sub-communities might be recognised as 'grimdark', 'inq28', or many other names, but really they were people who put narrative first and approached painting like it was a real *art*. 

Then of course in 2020 we had Covid, which for me in Aotearoa New Zealand meant lockdowns and plenty of time to paint. During that year I approached warhammer with new enthusiasm, testing out different techniques and styles, learning and experimenting. By the end of that year I realised I'd painted just over 1,000 points of models for my army, and was so excited at this discovery that I wrote my first hobby diary entry ("My first one thousand points"). It was a huge accomplishment given that during the preceeding four years I'd been unable to focus on a project or paint anything I was happy with. 

Between the end of 2020 and the end of 2023 I painted a lot - with many successes and failures - and wrote a total of 31 hobby diary entries. These entries ranged dramatically in size and scope, with some being short notes about things I wanted to do or something I'd seen, to large entries with a narrative. I stored these as single word documents in a folder on my computer which, as someone with experience in data science, is now horrifying. Sometime around the end of 2023 I transitioned into writing into a physical notebook which I definitely prefer (finding it much easier to get into the stream-of-conciousness style of writing). At the same time, and more into 2024, I started to write in a more organised digital hobby diary with the aim of one-day publishing it as a website and/or blog, but mostly because it was a better way to organise my documents.

We are now coming into the final quarter of 2025 and I've recently moved to Luxembourg. This has meant something of a fresh start with my hobby (although I did manage to pack some things with me) and it seems like a good time to really organise and make my writing and documentation process into something I'm happy with. I've realised I really enjoy writing and would love to create my own version of the types of articles and imagery that I saw in White Dwarf articles.


# Aims

What am I aiming for in the hobby? There are three main things:

#### 1. To create art that I am proud of

I have a long list of artists whose work I admire. These artists cover a wide range of techniques and some work in vastly different styles. I'm not committed to any one of these styles or techniques and want to practice and work in different ways. Work that I'm proud of means that I continue to *explore* and finish work to a *high standard*. 

#### 2. Be a better gamer

I see gaming as an integral part of this hobby. I want gaming to be fun and social, a chance to interact with other people who enjoy warhammer, to forge a narrative, and a chance for some friendly competetion. The aim "to be better gamer" doesn't mean "win more often" (although that would be nice). Being better means:

- Being able to field my forces like a proper general, making the best use of my units on the tabletop. Losing games isn't a problem, but having a unit of cavalry who never gets to charge because I'm bad at positioning will take the shine off of painting, I'm sure. 

- Knowing my rules well. Warhammer games are long and tiring, and I need to know both the rules of the game and the statistics and features of my units. This will make games both easier for me and more enjoyable for my opponent. 

- Keeping calm, accepting variance, not getting emotioanally tied to units or outcomes. Embracing each game as a shared narrative, rather than a competition. 

#### 3. Engage with the hobby via lore and narrative

The warhammer universe(s) are massive sandboxes, with huge potential for creativity. Like the online communities that kickstarted my enthusiasm in 2020, I want to imagine and create narrative. 

### Recording my process and progress

I have a fourth aim: to record my process and progress. In my physical hobby diary I noted how much I'd liked reading about the "Remembrancers" in the first Horus Heresy book. In this book the Space Marine Legions are accompanied by human "Remembrancers" - artists including painters, poets, and writers - who will document the process of the Great Crusade. I also follow a number of blogs (Iron Sleet, Warboss Kurgan, Animosity Campaigns, Gardens of Hecate, to name a few) who document their process and I enjoy reading these. 

# How this site works

Some pages will be written in real-time, and some will be 'historic' - updated copies of things that I wrote years ago. I'll also freely change or update things as I go if I think it makes sense, and in other cases I won't bother (*e.g.,* I might name a character one thing one day, then find a name I like more, and I might or might not go back and update the older entry).

I'll be recording painting recipes and ideas, project logs, and bits of narrative lore in the Hobby Diary section. I'll aim to use Projects as organisers and a way to have overviews. 

