---
title: slowgrowcampaign
---

## General Concepts 

In this campaign all escalation (xp, access to items etc.,) will happen as a group. Rather than xp, players are encouraged to discuss a story narrative - a general on a winning streak can boast of better morale, of well fed horses, and great renown. Meanwhile, a string of losses might prompt an act of (reckless) bravery from your general. These narrative facts don't have to be included in the rules to be reflected on the table. 

### Restrictions

The intention is to start as small as possible playing doubles with highly restricted lists. Your force should start at 500 points and be as basic as your theme allows. This includes, but is not limited to: 

- No lord level characters

- wizards level 1

- No magic items

- No monstrous mounts

- No unit upgrades (no Big'Uns, Chosen, Veterans) 

In short, paint your basic troops and remember leaders are not (yet) highly renowned! 

Access to wider list options will occur for everyone after a set amount of games at each points value, and will coincide with increases to game point limits. 

### Unit identity

Characters *must* be named. Units should be named. The idea is to keep unit "identity" throughout the campaign without letting this get in the way of gaming practicalities. For example, a unit of swordsmen might number 20 initially. As the campaign progresses the unit might grow to 30, or shrink to 15, as your points limits allow. In this way, you can keep the general identity of the unit and still be able to use unit size and options (e.g., shields). Narratively, this represents the actual unit being significantly larger than what is represented in any given battle and numbers fluctuate due to injury. The option to add or lose shields might indicate a unit had to move quickly, or stealthily, that morning. 

At a certain point in the campaign we will unlock upgraded units like Big'Uns, Chosen, Veterans etc.,. It might make thematic sense for this to be a new unit reinforcing your army, or it might be that an existing unit has earned the experience to be upgraded. Characters will work in the same way - while you start with the most basic version of leaders available, you can 'upgrade' the named hero to higher tiers of character option. 

### Gameplay

Games will start as doubles with 500 points each, and progress to doubles at 750 each, then either 1k doubles or 1k singles. Progression rates will be determined by the slowest painter. 


