---
title: Vampire Counts for a slow grow campaign
---


I will paint and play as the Vampire Counts in the planned slow-grow campaign. I'm trying out something like Wilhelm_miniatures contrast-and-dab technique, with added contrast work-ons. I may go in later with oil paints to increase value, time dependent. The army is already assembled, purchased as an army lot, and based correctly. Game-play wise I think the models and army list offers a lot of space to tailor thematically, and I'm optimistic that I can make the most of these rules to perform crushing hammer-and-anvil tactics. But I've been drastically wrong about my skills in the past, so I guess we will see how I go!

## Introduction to the Vampire Counts project

I bought an army-lot vampire counts force which was based for the Old World. It contained, roughly: a VC Lord on Dragon, a ghoul-king, and a banshee. There were two x 20 ghoul units, six each of crypt ghouls (large, poisoned claws) and vargheists (flying, armour-piercing, damage-dealers), and 12 dire wolves. Finally, five Blood knights, and a scattering of small monsters. 

To this I can add (via re-basing), 20 grave guard, five black knights, a wight king on skeletal steed, and a Blood Dragon Knight on foot. I plan to convert/scratch build a vampire count on knightmare, who will eventually ride with the five blood knights (though the vampire on knightmare will be a Von Carstein bloodline). 


## Narrative and gameplay experience

I'm writing these two together because they need to connect, fundamentally. I really want the vampire counts army to reflect the narrative I'll be telling. Makarov Edgar Von Carstein is a distant member of the bloodline, so lowly ranked as to have escaped attention during the Vampire Wars. During the wars Makarov fled early and now roams the Old World as a small warband comprised of his household knights, hounds and the implacable foot-guard. 

I plan to have Makarov eventually join my starting force, which is currently led by a blood knight on foot and has nothing but feral ghouls, monsters, and the like in his force. The as-yet-un-named blood knight will need to fight a few battles with this rabble before other, more orderly alliances can be called in. 

Gameplay wise, I'll do what I can to make this army feel scary: implacable, with a few fast elements, and damaging combat lords. Makarov will eventually be in magical armour (5+, 6++) that allows casting, mounted on a barded knightmare (4+), in a unit of five of blood knights who can issue and accept challenges. With the Drakenhoff banner all models in the unit will imrove their regeneration by one point, giving Makarov 4+, 6++, 4+++. I like that he will be *extremely* durable, as one would expect from a mounted vampire knight, but is still vulnerable to Killing Blow. With the Sword of Kings, Makarov has killing blow 5+, so I'm hoping for some tense challenges where it's first to strike a killing blow. 

I don't want to go too deep into the hero-hammer aspect of this faction, so aside from the most powerful non-monster lord I could think of, I'll keep the army to cheap characters and a strong focus on the core units. Cheap characters mean baseline vampires, wights, or necromancers to provide their key aspect, no magical items. I think the ghouls are going to be an interesting way to start the campaign: skirmishing damage dealers with move-through-cover and poison could prove to be potent damage dealers...or they might be too frail to do much if shot or out-struck. Having a big beefy unit of crypt horrors to back them up should be fun. In the mid-term, I'll aim to add monsters quickly (as quick-to-paint high cost models) and work towards adding the unit of grave guard and wight. 

Narratively, this faction is a little bit Viking. These are raiders who are straddling the lines and barriers of forces and empires. Ghouls and wolves need food, and the blood knight is gathering up as much coin and gold as possible, knowing it's value to the rest of the world. When the blood knight eventually meets Makarov, he will instictuallly identify with this well organised leader and is comfortable in allying himself with the Von Carstein. For Makarov, the blood knight is a disciplined, capable addition to the forces under his command. Makarov trusts the blood knight to keep his word, for as long as Makarov himself is holding to his end of the agreement and he is leading them well. 

## Hobby aspect

I am aiming to paint the troops (40 ghouls) quickly, since they are already sprayed white I'll use contrast and dabbing removal to stain and colour the ghouls with pale, sickly skin, sinister red faces and un-alived blackened hands. The wolves will get a similar treatment, but since they haven't been sprayed white I'll probably use a different technique (maybe gouache) to get somewhere. The Crypt Horrors, which I did as a test unit, are quite bright, which gives them a noble-bright villain appearance, and is also somewhere reminiscent of a clown's face painting. The grave guard will be the biggest painting commitment, and I want them to straddle grimdark and noble-bright. They will look deeply weathered and worn, textured, and slightly ghostly. Faded dark red features in their iconography. The black knights will take the grave guard template and elevate it. Older, more baroque, weathered, but more animated. 

The centrepiece of this force will be five baroque blood knights in metallic red, with the black-armoured, knightmare-mounted general. For this knightmare I imagine an empire horse with elongated legs, baroquely over-decorated armour and a pile of skulls in place of the knight horse-head. Or something equally terrifying. It's going to be all an almost-black brown, which fades whiter as it gets closer to the black of the vampire.

I haven't decided on the bases yet, and that's a huge issue. I don't want to go with something as simple as brown root mess, but maybe I should. I could possibly do something boggy, since the models are already glued to the base and I'm basing on top of that (the models will look slightly sunk ito the earth). I don't want to do any type of water effect, and want to keep it simple. I will aim for tall grasses, like rushes, to obscure and use a generally dark tone. 
