---
title: "Episode 002: Nurgle Marked Warriors of Chaos"
subtitle: "Getting back into Warhammer Fantasy"
categories: [Warhammer, Painting]
---

Without a doubt my favourite miniatures I've worked on, both for nostalgia and the paintjob I accomplished, are the Warhammer Fantasy 6th edition Chaos Knights. I painted a unit of five of these late in 2024 and I think they are just superb - everything I ever wanted out of Warhammer when I was a kid just getting into the hobby without much money. They form the core of my growing Warhammer fantasy chaos army and I'm planning to do a dedicated historical post about them at some point in the future. Briefly, this army is an homage to all the things I saw and loved about the release of Warriors of Chaos for Warhammer Fantasy's 6th edition, sometime around 2001 - 2002. A big part of what I recall are Paul Sawyer's White Dwarf articles (my first encounter with the 'slow-grow' format, something beloved by many people) which were mostly grounded and gritty, in black armour and gold trim. I also want to bring in a few other elements such as the more 'chaotic' nature that was present in some of the older editions, and to try and capture a human element (both by showing the tragic humanity of Chaos Warriors and contrasting that with the in-human nature of many of the models). This article is all about how the newest additions to the army touch on those chaotic and human aspects: a unit of Nurgle marked Chaos Warriors and a Nurgle Marked Sorcerer on Steed

Sometime in late 2024 I saw a sales post for some metal (definitely genuine, 100% not recast) Warhammer Fantasy chaos models for a very reasonable (almost too good to be true) price. I picked up two units that came from *pre*-sixth edition - one of which was a unit of Tzeentch marked warriors and the other a unit of Nurgle marked warriors. Being pre-sixth edition the models have much more of a chaotic nature than the uniformed, armoured forces that were typical of sixth edition chaos warriors and this was initially a bit jarring for me but it presented an interesting challenge. One of the first things I did hobby-wise on arriving in Luxembourg was start to base the unit of Nurlge marked warriors. This was more difficult than I expected due to the old models being built for 'slotta bases', which a metal bar that connects below the feet of the model. I didn't have slotta bases (in fact I had cheap mdf bases) so I experimented with cutting/snapping off the bar (works well for some models but not others), carving hole in the mdf board (difficult, don't recommend), and building up a base of stone and cork that could disguise the attached bar. On the plus side, these models didn't require assembly and being made of metal I didn't even attempt to tackle the mold lines. All in all, not too bad. The other unit I added was the Nurlge Marked Chaos Sorcrer on Steed. Direct from Sixth edition this model was one I recognised from White Dwarf and it was one I had been really excited to add to my collection when I saw it available. It's absolutely excellent, and one of three character models I have acquired from that period that I love. I was missing a weapon hand and gave it a suitably rusted, pitted, wickedly curved sword from the Cursed City skeleton sergeant, which works perfectly as a cavalry sabre (not that I expect him to be swinging it at anyone, but we will see). I also added a crow, again from Curse City, sitting on the back of the horse behind the rider to balance how it looks from a profile view (the torse splits the model mostly in two, but between the horses's head and the raise weapon arm I wanted something behind the rider). Aside from that the model went together easily, I think I filled the gaps with PVA glue since I didnt' have any greenstuff at the time. The base was made from glueing two 25mm mdf bases together. 

Painting these models took quite a while and I actually painted them off and on, taking a big break between finishing the models and coming back to basing them (and doing some touch-ups to the Sorcerer). I was struggling with not having exactly the paints I wanted, not having anywhere to prime the models with a rattlecan (apartment living is a new experience), not specific on my vision (where they fit on the continuum between black metal sixth edition and wild colours of previous chaos warriors). Mostly they were a mix of contrast paints and a few other bits and pieces, loosly following the recipe I used for the Chaos Knights which comes from Koltti's Patreon and being very free to add colour within the purple-green-orange triangle that I associate with Nurgle. I really like how some of these miniatures have tiny nurglings resting on their shoulders or helmets and it hints at the more 'goofy' aspect of Warhammer that I think I missed when I was younger. Another reason I struggled to get the warriors finished is that I realised I only had eight suitable models, which wasn't enough to form a proper unit. I knew at some point I'd need to find some additions, probably through heavily converting some models or using unit fillers. At the time I wasn't really ready to jump into that, so the eight warriors were put aside as soon as they were painted to a good enough standard. 

I then switched my attention to the Sorcerer. I started out making the armour quite yellow (yellow being the extreme 'highlight' of green), and focused on making the horse a mixture of orange and pink (not explicitely orange and pink, which would have been ridiculous, but using browns and other colours mixed with those colours to give hints of orange and pink). I won't pretend I had planned it out this way, I was just painting instinctively, but conceptually I think this works: I've basically managed to complete the purple-green-orange triangle again, but using very different colours. It was about this time that I took the long break mentioned above because I wasn't really happy with how the model was looking. After my long break I recently went back to the model and significantly darkened the armour and made a few other small changes, and I'm now much happier. 


