---
title: A resource is meaningless unless eventually expended
---

"A resource is meaningless unless eventually expended" 

                                    - Robert Jordan, The Wheel of Time

I'm facing the prospect of moving country in less than six months. I need to take stock of my current list of miniatures, bitz, and projects and then make a plan for how I will spend my hobby time between now and leaving. This will also include thinking about what hobby things I'll keep, take, and sell. Now is the time to use all the cool bitz, bases, paints, and materials I've been saving up. 


## A quick list of my currently painted army projects

**Warhammer The Old World Orcs and Goblins** - this is approximately a 1,500 point army. Still left to go in this project are some night goblins, another five wolf-riders, and a wolf-rider chariot which I might convert to be a character. Ambitiously, I might try and convert one of the wolf-riders to be a shaman (who would otherwise just be a cool looking unit boss). 

**Ultra Legion** - 1,500 to 2k Space Marines. Still to go in this project are five jump pack intercessors and a Gladiator tank. 

**The Achillian Majesty** - Current points unknown, maybe 1,500? Still to go in this project is completing the Terminator squad, who I'm not happy with, a converted Terminator Lord and the Land Raider "The Ruin". 

**Warhammer The Old World Chaos** - A unit of Chaos Warriors I need to base, a unit of Knights (my favourite miniatures, with probably my favourite paint job), and three Ogors. In terms of it's status as a project, there is a lot I want to do with this and have plenty of models. It's currently top of my list for things I want to transport. 

**Warhammer The Old World Vampire Counts** - A unit of ghouls, and a unit of Crypt Horrors. Lots I can do with this project, but it's fallen out of favour. 

**Renegade Astartes** - Ten Heretic Astartes, three Bikers. A converted command rhino and predator are built and primed. Along with the Old World Chaos, this is probably the project with the most potential space. 